### ISSUE TITLE
Add getPost API endpoint

### ISSUE THREAD

**Issue by TwoDCube** [Verseghy/website_backend#15]

**Comment by Sasszem** [comment]
Instead of
### GET vfg.api/posts/getPost?post={id}
we should write
### GET vfg.api/posts/getPost/{id}
or
### GET vfg.api/posts/getPostById/{id}
because other API endpoints follow this naming convention

**Comment by TwoDCube** [comment]
I think it would be better as
## GET vfg.api/posts/getPostById?id={id}
