### ISSUE TITLE
Add archive backend

### ISSUE THREAD

**Issue by Sasszem** [Verseghy/website_backend#230]

**Comment by TwoDCube** [comment]
The proposed workings of the API can be accessed here: https://app.swaggerhub.com/apis-docs/TwoDCube/verseghy-archive/1.0.0

Any comments for the proposal are welcome

**Comment by Sasszem** [comment]
Ok, base idea: 
We have 2 API endpoints. The first returns a JSON list with objects, each object has a date (year and month only - may be just a string), and a number representing the number of posts in that month. There might be an opting to limit how far do we want to go back.
The second API endpoint returns all posts by year and month.

Implementing the first can be done by simply counting and grouping, the second one is filtering. Caching will be applied on the SQL side, so it would be reasonably fast.

**Comment by Sasszem** [comment]
Both endpoints can go under Posts, I think.
