### ISSUE TITLE
Support for tables editing in post content

### ISSUE THREAD

**Issue by TwoDCube** [Verseghy/website_backend#356]
We need to support editing tables in the post content's wysiwyg editor. The current implementation uses https://github.com/sparksuite/simplemde-markdown-editor which does support tables but it has to be enabled using the `showIcons: ["table"]` attribute.

We need to evaluate how usable this really is, because the other editor laravel backpack supports (https://summernote.org/) supports pasting tables from a different source, even keeps the formatting of the borders and the alignment and styles of the text and things like that. If the current MD editor is not as good we should consider switching our current implementation of storing markdown and parsing it to the frontend to storing HTML.

**Comment by Sasszem** [comment]
https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/fields/simplemde.blade.php

Lines 9 & 10 show how to pass attributes
