### ISSUE TITLE
Add ML for post recommendation system

### ISSUE THREAD

**Issue by TwoDCube** [Verseghy/website_backend#53]
![](http://latex2png.com/output//latex_b9c864b64ac8f5978553e31dfd603492.png)

Where:
`Tetha 1 2 3 4` is the user's feature vector
`n_u` the number of users
`r(i,j)=1` if the j user saw the i post
`xi` the i post's category vector
`y ij` the user's rating (how long did they stay reading the post / words in the text)
`lambda` fine tuneable constant for the irregularization term

**Comment by Sasszem** [comment]
Api endpoint:
`GET /posts/getRecommends?mldata=DATA`
where `DATA` is a serialized JSON Object, where keys are the IDs of the posts viewed(and thus scored) by the user, and the values are the according scores.

If MLData is empty, then send 3(**n**) newest

**Comment by TwoDCube** [comment]
This is VHD-10
