### ISSUE TITLE
Add search engine

### ISSUE THREAD

**Issue by TwoDCube** [Verseghy/website_backend#57]
We need a search engine which support searching by:
- Posts title
- Posts description
- Posts content
- Posts label
- Authors name

The search should be case insensitive.

Suggestion:
Because most people in hungary write without using accents match also words like `gimnazium` to `gimnázium`.

### GET `vfg.api/search?term={searchterm}`
It should return all of the posts which match any of those listed above with `_makeThumbnail`

**Comment by Sasszem** [comment]
What is the single `term` parameter?

**Comment by Sasszem** [comment]
I think we should not `OR` the terms, instead `**AND` them**
